/* -*-c++-*- OpenRTI - Copyright (C) 2009-2010 Mathias Froehlich
 *
 *
 * This file is part of OpenRTI.
 *
 * OpenRTI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * OpenRTI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with OpenRTI.  If not, see <http://www.gnu.org/licenses/>.
 *
 * This file is autogenerated by messagegen.py. Do not edit!
 *
 */

#ifndef OpenRTI_TightBE1MessageEncoder_h
#define OpenRTI_TightBE1MessageEncoder_h

#include "AbstractMessageEncoder.h"
#include "EncodeDataStream.h"
#include "Export.h"
#include "Message.h"
#include "NetworkBuffer.h"

namespace OpenRTI {

class OPENRTI_LOCAL TightBE1MessageEncoder : public AbstractMessageEncoder {
public:
  TightBE1MessageEncoder();
  virtual ~TightBE1MessageEncoder();

  virtual const char* getName() const;

  virtual void encodeMessage(NetworkBuffer& networkBuffer, const AbstractMessage& message);

private:
  class DispatchFunctor;
  class EncodeStream;
};

} // namespace OpenRTI

#endif
